name: libs/server-sdk-otel

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ "main", "feat/**" ]
    paths-ignore:
      - '**.md'
  schedule:
    # Run daily at midnight PST
    - cron: '0 8 * * *'

jobs:
  build-test-otel:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.3.0
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: ./.github/actions/ci
        with:
          cmake_target: launchdarkly-cpp-server-otel
          install_curl: true
          # We don't produce release artifacts.
          simulate_release: false
  build-otel-mac:
    runs-on: macos-13
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.3.0
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: ./.github/actions/ci
        with:
          cmake_target: launchdarkly-cpp-server-otel
          platform_version: 12
          install_curl: true
          # We don't produce release artifacts.
          simulate_release: false
  build-test-otel-windows:
    runs-on: windows-2022
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.3.0
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      # https://github.com/ilammy/msvc-dev-cmd/releases/tag/v1.13.0
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
      - uses: ./.github/actions/ci
        env:
          BOOST_LIBRARY_DIR: 'C:\local\boost_1_87_0\lib64-msvc-14.3'
          BOOST_LIBRARYDIR: 'C:\local\boost_1_87_0\lib64-msvc-14.3'
          Boost_DIR: 'C:\local\boost_1_87_0\lib64-msvc-14.3\cmake\Boost-1.87.0'
        with:
          cmake_target: launchdarkly-cpp-server-otel
          platform_version: 2022
          toolset: msvc
          install_curl: true
          # We don't produce release artifacts.
          simulate_windows_release: false
